# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'precise64'
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
  config.vm.hostname = 'vagrant'
  config.vm.network :private_network, ip: '192.168.33.10'
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: 'ssh'

  config.vm.provision :ansible do |ansible|
    ansible.inventory_path = 'ansible/development'
    ansible.playbook = 'ansible/site.yml'
    ansible.verbose = 'v'
    ansible.limit = 'all'
  end
end
